#!/usr/bin/ansible-playbook
---
#      Copyright (c) 2016, 2017 World Wide Technology, Inc.
#      All rights reserved.
#
#      Revision history:
#        5 October 2016      |  1.0 - modified for vagrant
#       10 Janary 2017       |  1.1 - added additional local modules for training class
#       20 January 2017      |  1.2 - added cisco_ios_show.py
#
- name: Install modules to run the Automation of F5 Initial Setup playbook
  hosts: localhost
  gather_facts: yes

  vars:
   path:
     target: "/usr/share/ansible/"
     source: "https://raw.githubusercontent.com/"

   programs:
     - {repo: "joelwking/ansible-nxapi/master/", fn: csv_to_facts.py, dn: "{{path.target}}" }
     - {repo: "joelwking/ansible-f5/master/", fn: icontrol_install_config.py, dn: "{{path.target}}"}
     - {repo: "mamullen13316/ansible_xls_to_facts/master/", fn: xls_to_facts.py, dn: "{{path.target}}"}
     - {repo: "joelwking/ansible-nxapi/master/", fn: nxapi_install_config.py, dn: "{{path.target}}"}
     - {repo: "joelwking/ansible-aci/master/", fn: aci_install_config.py, dn: "{{path.target}}"}
     - {repo: "joelwking/ansible-aci/master/", fn: AnsibleACI.py, dn: "{{path.target}}"}
     - {repo: "joelwking/ansible-aci/master/", fn: aci_gather_facts.py, dn: "{{path.target}}"}
     - {repo: "joelwking/ansible-aci/master/", fn: aci_clone_tenant.py, dn: "{{path.target}}"}
     - {repo: "joelwking/ansible-ios/master/", fn: cisco_ios_install_config.py, dn: "{{path.target}}"}
     - {repo: "joelwking/ansible-apic-em/master/", fn: apic_em_gather_facts.py, dn: "{{path.target}}"}
     - {repo: "joelwking/ansible-f5/master/", fn: icontrol_gather_facts.py, dn: "{{path.target}}"}
     - {repo: "joelwking/ansible-spark/master/", fn: spark_room.py, dn: "{{path.target}}"}
     - {repo: "joelwking/ansible-f5/master/", fn: F5_sdk_LTM_node.py, dn: "{{path.target}}"}
     - {repo: "joelwking/ansible-module-infoblox/molina/", fn: infoblox.py, dn: "{{path.target}}"}
     - {repo: "joelwking/ansible-f5/master/", fn: bigip_check.py, dn: "{{path.target}}"}
     - {repo: "joelwking/ansible-ios/master/", fn: cisco_ios_show.py dn: "{{path.target}}"}

   playbooks:
     - {repo: "mwallco/f5_ansible/master/", fn: f5_initial_setup.yml, dn: "/home/vagrant/f5toolkit/ansible/playbooks/"}

   files:
     - {repo: "mwallco/f5_ansible/master/", fn: f5_initial_setup.csv, dn: "/home/vagrant/f5toolkit/ansible/playbooks/files/"}

  tasks:
  - name: Download the Playbook Example CSV and modules
    uri:
      method: GET
      url: "{{path.source}}{{item.repo}}{{item.fn}}"
      dest: "{{item.dn}}"
      validate_certs: no
    with_items:
      - "{{programs}}"
      - "{{playbooks}}"
      - "{{files}}"
      
  - name: chmod on modules and playbooks(s)
    command: "/bin/chmod 755 {{item.dn}}{{item.fn}}"
    with_items:
      - "{{programs}}"
      - "{{playbooks}}"

  - name: dos2unix on the modules
    command: "/usr/bin/dos2unix {{item.dn}}{{item.fn}}"
    with_items:
      - "{{programs}}"
