#!/usr/bin/ansible-playbook
---
#      Copyright (c) 2016 World Wide Technology, Inc.
#      All rights reserved.
#
#      Revision history:
#        5 October 2016      |  1.0 - modified for vagrant
#
- name: Install modules to run the Automation of F5 Initial Setup playbook
  hosts: localhost
  gather_facts: yes

  vars:
   path:
     target: "/usr/share/ansible/"
     source: "https://raw.githubusercontent.com/"

   programs:
     - {repo: "joelwking/ansible-nxapi/master/", fn: csv_to_facts.py, dn: "{{path.target}}" }
     - {repo: "joelwking/ansible-f5/master/", fn: icontrol_install_config.py, dn: "{{path.target}}"}
     - {repo: "mamullen13316/ansible_xls_to_facts/master/", fn: xls_to_facts.py, dn: "{{path.target}}"}

   playbooks:
     - {repo: "mwallco/f5_ansible/master/", fn: f5_initial_setup.yml, dn: "/home/vagrant/f5toolkit/ansible/playbooks/"}

   files:
     - {repo: "mwallco/f5_ansible/master/", fn: f5_initial_setup.csv, dn: "/home/vagrant/f5toolkit/ansible/playbooks/files/"}

  tasks:
  - name: Download the Playbook Example CSV and modules
    uri:
      method: GET
      url: "{{path.source}}{{item.repo}}{{item.fn}}"
      dest: "{{item.dn}}"
      validate_certs: no
    with_items:
      - "{{programs}}"
      - "{{playbooks}}"
      - "{{files}}"
      
  - name: chmod on modules and playbooks(s)
    command: "/bin/chmod 755 {{item.dn}}{{item.fn}}"
    with_items:
      - "{{programs}}"
      - "{{playbooks}}"

  - name: dos2unix on the modules
    command: "/usr/bin/dos2unix {{item.dn}}{{item.fn}}"
    with_items:
      - "{{programs}}"
